# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5fb0a1b412cbc8e3589a343466bcdf833427e57d65f43fc4a5f69cbeeec76de83a71a096e3ad9f2ba774a4fa0b6f6235d9da7c44ea175af54fb9f9f4f6e94364

test:
  secret_key_base: 16607973e8a6e464ac603601bb3cef4e51240aa4d325265d3fe6d21edd3886cd69b8a8e221eca5538dd4bffc2ca937afb94899d45f325e2654941f63de04b887

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
